# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright-Folio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: microsoft/playwright-github-action@v1    
    - run: npm install
    - name: Execute Playwright Tests
      run: npx folio --param browserName=chromium
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: report
